version: '2'

services:
        web:
            image: nginx:latest
            ports:
                - "80:80"
                - "443:443"
            volumes:
                - ./app/:/var/www/app
                - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
                - ./docker/logs/nginx:/var/log/nginx
            links:
                - backend
        backend:
            build:
                context: "./docker/php-fpm"
            ports:
                - "9080:9000"
                - "8080:8080"
            volumes:
                - ./app/:/var/www/app
                - ./docker/config/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
                - ./docker/config/php-fpm/php.ini:/usr/local/etc/php/php.ini
            links:
                - mysql:mysql
        mysql:
            build:
                context: "./docker/mysql"
            ports:
                - "3306:3306"
            volumes:
                - ./docker/.data/db:/var/lib/mysql
                - ./docker/config/mysql:/etc/mysql/conf.d
                - ./mysql_dump/:/var/tmp/mysql_dump/
            command:
                - --innodb-buffer-pool-size=1073741824
                - --sort_buffer_size=1073741824
volumes:
    db-data:
        external: false
    elasticsearch-data:
        external: false